### PR TITLE
Optimize JBB Profile Execution with Fixed Parameters and Conditional Logic

### PR DESCRIPTION
**Pull request by mittaltarkik**
Description:
This PR introduces improvements to the new profile by addressing the complexity arising from 16+ parameters for user configurations. In the JBB profile, running tests had become challenging due to varying parameter values.

Key improvements include:

Fixed Parameter Values: After thorough discussions with Alex, we have locked down the values of these parameters. This change simplifies the configuration process and ensures more predictable performance.
Ternary Operator Implementation: A ternary operator has been introduced to make runtime decisions dynamically. The logic now adjusts based on system configuration and user input, improving flexibility and adaptability during execution.

### CODE REVIEW

**Review by deep1712 — APPROVED** [review]

**Comment by yangpanMS** [comment]
Hi Tarkik, this is highly internal specific, please move this to the internal repo and name it accordingly.

**Comment by alexffrank** [comment]
@tarkik, could you please describe testing performed for the new profile?

**Review by yangpanMS — CHANGES_REQUESTED** [review]
As previously mentioned, please move this to internal repo and name it accordingly. You could use compete as the prefix in the internal repo.

**Comment by mittaltarkik** [comment]
> As previously mentioned, please move this to internal repo and name it accordingly. You could use compete as the prefix in the internal repo.

Hi Yang, I have created a new PR internal repo and marked you as reviewer.

**Comment by mittaltarkik** [comment]
Closing this PR as this change moved to internal repo.

**Pull request closed without merging**
