### PR TITLE
Fixing metadata flow for the virtual client component from CommandLine

### PR DESCRIPTION
**Pull request by deep1712**

### CODE REVIEW

**Review by yangpanMS — APPROVED** [review]

**Comment by yangpanMS** [comment]
Thanks for spotting this. We should try verifing this in unit test

**Comment by yangpanMS** [comment]
Also bump version if you need new build

**Comment by deep1712** [comment]
> Thanks for spotting this. We should try verifing this in unit test

Added unit tests it made sense  :)

**Comment by deep1712** [comment]
> Also bump version if you need new build

Bumped

**Review by imadityaa — APPROVED** [review]

**Review by yangpanMS — APPROVED** [review]

**Pull request merged**
