### PR TITLE
Added dependency to install Nvidia GRID driver on Linux and Windows

### PR DESCRIPTION
**Pull request by ahkhaldi**

### CODE REVIEW

**Comment by yangpanMS** [comment]
As discussed, please help add basic unit tests and documents

**Comment by yangpanMS** [comment]
Hi @ahkhaldi did you still need this PR. Did you have time to work on the documents and unit tests?

**Comment by ahkhaldi** [comment]
Hi Yang,

We might move this code to our new HPC extension. I think we can cancel this PR for now.
Sorry I was busy working on other projects and didn't have the time to work on documentation and unit tests.

Thanks,
Ahmad

**Comment by yangpanMS** [comment]
Thank you @ahkhaldi let me know if you need anything else. Closing this for now

**Pull request closed without merging**
